### ISSUE TITLE
Problems when checking dplyr release candidate

### ISSUE THREAD

**Issue by krlmlr** [numeract/Nmisc#9]
For some reason, trying to run R CMD check on this package with a dev version of _dplyr_ installed gives a check error. I suspect that the tests are not prepared for this condition. Can you confirm?

https://github.com/tidyverse/dplyr/blob/b7a8f540e9b07d4a9a86a30318605a0bca359cdf/revdep/new-problems.md#nmisc

**Comment by MikeBadescu** [comment]
@krlmlr, thank you for letting me know. 

I push the changes to fix this issue and I submitted a new version to CRAN. Please let me know whether you encounter other issues.

(While my package should not have a problem with the new version of dplyr, it was not prepared for the test environment used. Thus, that particular tests are now skipped if not tested on a local dev machine.)

**Comment by krlmlr** [comment]
Amazing, it's on CRAN already! Thanks a lot!
